[package]
name = "implemented_CAL_environment"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto-layer = {version="0.1.0", path="binaryknights_rust_crypto", features=["macos", "tpm"]}
openssl-sys = "0.9.102"
slint = "1.6"

[build-dependencies]
slint-build = "1.6"
